### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by woodwm** [FilippoAiraldi/metanet#1]
Hi,

Thanks for sharing the great package. I can see some comments on the model calculation. Could you add references for the model?

**Comment by FilippoAiraldi** [comment]
Hello!

if with references you mean the equations that I mention in, e.g., `metanet/sim/functional.py`, then I mainly used [this PhD Thesis](http://web.dcsc.tudelft.nl/~bdeschutter/research/phd_theses/phd_hegyi_2004.pdf). In Chapter 3, the authors describe the METANET modelling framework in a decent way. Hope it can help!

Thanks for highlighting the issue, btw.

Filippo
