### ISSUE TITLE
Question about node equations when number of upstream link is 1 

### ISSUE THREAD

**Issue by YSXXXXXXX** [FilippoAiraldi/metanet#3]
Hi,
Thank you for the excellent package and repository.
I have a question on how to get the upstream flow of a link (i.e. $q_0$) if the number of the upstream link is one. In [src/sym_metanet/blocks/nodes.py Line111-Line116](https://github.com/FilippoAiraldi/sym-metanet/blob/1b6b96d1d5208b9dfbfdd221d3aaa7418a37adbf/src/sym_metanet/blocks/nodes.py#L111C1-L116C62), it seems that $q_0=q_{\mu,N_\mu}$ , maybe it cannot deal with the case shows in the following picture.
![case1](https://github.com/FilippoAiraldi/sym-metanet/assets/98463936/279a7b1a-4f3e-46be-91c7-91dc57b63b0f)

In this case, I think $q_0=Turn Rate\times q_{\mu,N_\mu}$ .
I'm not sure whether I understand the code correctly, hope you reply.

**Comment by FilippoAiraldi** [comment]
Hello!

If I recollect the METANET theory correctly, I believe that in the picture you shared the upstream flow of Link1 would be the flow of the upstream link, minus the flow of vehicles leaving via the off-ramp. Correct me if I am wrong, please!

This is not a scenario that the package can deal with yet, as at the time of its creation I was focusing more on scenarios where the destination absorbs all the incoming traffic. However, it should not be too difficult to implement it

1. First of all, you would need the equations governing the off-ramp dynamics, i.e., flow and, if any queue length.
2. Then, these equations can be implemented in the [`DestinationEngine`](https://github.com/FilippoAiraldi/sym-metanet/blob/1b6b96d1d5208b9dfbfdd221d3aaa7418a37adbf/src/sym_metanet/engines/casadi.py#L175) of choice, e.g., CasADi or NumPy. As you can see, as of now the engine only allows to compute downstream densities, so it is limited.
3. Implement in the `blocks` folder a class to wrap this functionalities, e.g., `OffRamp`, or equivalently expand a destination class already present in the package.
4. Last point, in the node's upstream computations, also take into account whether there are off-ramps that can absorb a portion of the upstream flow.

I hope this can help. If you have any other doubts, please let me know!

**Comment by YSXXXXXXX** [comment]
Thank you for your kind reply.
> If I recollect the METANET theory correctly, I believe that in the picture you shared the upstream flow of Link1 would be the flow of the upstream link, minus the flow of vehicles leaving via the off-ramp. Correct me if I am wrong, please!
> 
> This is not a scenario that the package can deal with yet, as at the time of its creation I was focusing more on scenarios where the destination absorbs all the incoming traffic. However, it should not be too difficult to implement it
> 
> 1. First of all, you would need the equations governing the off-ramp dynamics, i.e., flow and, if any queue length.
> 2. Then, these equations can be implemented in the [`DestinationEngine`](https://github.com/FilippoAiraldi/sym-metanet/blob/1b6b96d1d5208b9dfbfdd221d3aaa7418a37adbf/src/sym_metanet/engines/casadi.py#L175) of choice, e.g., CasADi or NumPy. As you can see, as of now the engine only allows to compute downstream densities, so it is limited.
> 3. Implement in the  folder a class to wrap this functionalities, e.g., , or equivalently expand a destination class already present in the package.`blocks``OffRamp`
> 4. Last point, in the node's upstream computations, also take into account whether there are off-ramps that can absorb a portion of the upstream flow.

I think you are right. I agree with you.
By the way, I noticed that the examples in `examples` do not have lane drop bottleneck scenarios, could you provide me with a reference value (order of magnitude) for the parameter $\phi$ ? Thank you in advance.

**Comment by FilippoAiraldi** [comment]
This [paper](https://www.sciencedirect.com/science/article/pii/S0968090X01000055?casa_token=ZOdV4pxLz0IAAAAA:vHGPAPMqMJqocN-kqDoa1NK-L0GxmokH_r0JKw4onjWK_Znk0FRr7Qahflz-3XJr4Rof_0Vb-LU) uses $\phi = 2.98$, and the authors are very credible.

**Comment by YSXXXXXXX** [comment]
I will read it. Thank you so much, I think we can close this issue now.
